### ISSUE TITLE
t/formatstl_load.t hangs on FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [pryrt/App-Generate3dMesh#13]
See subject. The test suite hangs on my FreeBSD smokers (various OS versions: 9, 10, 13, 14) while running t/formatstl_load.t. The output of the test script:
```
EOF? at /usr/home/cpansand/.cpan/build/2021112322/CAD-Mesh3D-0.005-0/blib/lib/CAD/Mesh3D/FormatSTL.pm line 335.
EOF? at /usr/home/cpansand/.cpan/build/2021112322/CAD-Mesh3D-0.005-0/blib/lib/CAD/Mesh3D/FormatSTL.pm line 335.
EOF? at /usr/home/cpansand/.cpan/build/2021112322/CAD-Mesh3D-0.005-0/blib/lib/CAD/Mesh3D/FormatSTL.pm line 335.
EOF? at /usr/home/cpansand/.cpan/build/2021112322/CAD-Mesh3D-0.005-0/blib/lib/CAD/Mesh3D/FormatSTL.pm line 343.
t/formatstl_load.t .. 
```

**Comment by pryrt** [comment]
Those tests only important on Windows with binmode issues, so I will skip them for FreeBSD.
closed with 4dfaa73

**Comment by pryrt** [comment]
Actually, I'll re-open until it's gone through your smoketesting.

**Comment by pryrt** [comment]
`[2021-11-25T22:23:33Z] [Slaven Rezi&#x107;] [fail] [PETERCJ/CAD-Mesh3D-0.006.tar.gz] [amd64-freebsd] [perl-v5.10.1] [535a466e-4e3e-11ec-be6d-23631f24ea8f] [2021-11-25T22:23:33Z]`

Not sure why it's still failing.  I spun up a FreeBSD VM and with my skip_all, it was able to pass the two formatstl test files by bypassing them.  I thought I had checked the others already.  I guess I should have kept the VM available a bit longer, and done more testing. :-(

**Comment by pryrt** [comment]
Apparently, I hadn't properly tested STL-unpatched.t in FreeBSD after making the changes to the module -- I verified it was failing, and fixed it so I can make it pass on my FreeBSD experiments. Hopefully, [this](https://github.com/pryrt/CAD-Mesh3D/releases/tag/v0.006001) will work.

**Comment by pryrt** [comment]
```
[2021-11-26T00:29:23Z] [Slaven Rezi&#x107;] [pass] [PETERCJ/CAD-Mesh3D-0.006001.tar.gz] [amd64-freebsd] [perl-v5.20.0] [e7a5747c-4e4f-11ec-97a4-e82b1f24ea8f] [2021-11-26T00:29:23Z]
```
looks like it's working now.
